/*
 * generated by Xtext
 */
package org.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.ui.internal.PlantumlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PlantumlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PlantumlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PlantumlActivator.getInstance().getInjector(PlantumlActivator.ORG_XTEXT_PLANTUML);
	}
	
}
