/*
 * generated by Xtext
 */
package org.xtext.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.services.PlantumlGrammarAccess;

public class PlantumlParser extends AbstractContentAssistParser {
	
	@Inject
	private PlantumlGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.ui.contentassist.antlr.internal.InternalPlantumlParser createParser() {
		org.xtext.ui.contentassist.antlr.internal.InternalPlantumlParser result = new org.xtext.ui.contentassist.antlr.internal.InternalPlantumlParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getInstructionAccess().getAlternatives(), "rule__Instruction__Alternatives");
					put(grammarAccess.getSequenceAccess().getAlternatives(), "rule__Sequence__Alternatives");
					put(grammarAccess.getDefinitionAccess().getAlternatives(), "rule__Definition__Alternatives");
					put(grammarAccess.getColorAccess().getAlternatives_1(), "rule__Color__Alternatives_1");
					put(grammarAccess.getDiagramAccess().getGroup(), "rule__Diagram__Group__0");
					put(grammarAccess.getInstructionAccess().getGroup_0(), "rule__Instruction__Group_0__0");
					put(grammarAccess.getInstructionAccess().getGroup_0_3(), "rule__Instruction__Group_0_3__0");
					put(grammarAccess.getInstructionAccess().getGroup_3(), "rule__Instruction__Group_3__0");
					put(grammarAccess.getSequenceAccess().getGroup_0(), "rule__Sequence__Group_0__0");
					put(grammarAccess.getSequenceAccess().getGroup_1(), "rule__Sequence__Group_1__0");
					put(grammarAccess.getSequenceAccess().getGroup_2(), "rule__Sequence__Group_2__0");
					put(grammarAccess.getSequenceAccess().getGroup_3(), "rule__Sequence__Group_3__0");
					put(grammarAccess.getSequenceAccess().getGroup_4(), "rule__Sequence__Group_4__0");
					put(grammarAccess.getSequenceAccess().getGroup_5(), "rule__Sequence__Group_5__0");
					put(grammarAccess.getSequenceAccess().getGroup_6(), "rule__Sequence__Group_6__0");
					put(grammarAccess.getSequenceAccess().getGroup_7(), "rule__Sequence__Group_7__0");
					put(grammarAccess.getSequenceAccess().getGroup_8(), "rule__Sequence__Group_8__0");
					put(grammarAccess.getSequenceAccess().getGroup_9(), "rule__Sequence__Group_9__0");
					put(grammarAccess.getSequenceAccess().getGroup_10(), "rule__Sequence__Group_10__0");
					put(grammarAccess.getSequenceAccess().getGroup_11(), "rule__Sequence__Group_11__0");
					put(grammarAccess.getSequenceAccess().getGroup_12(), "rule__Sequence__Group_12__0");
					put(grammarAccess.getSequenceAccess().getGroup_13(), "rule__Sequence__Group_13__0");
					put(grammarAccess.getSequenceAccess().getGroup_14(), "rule__Sequence__Group_14__0");
					put(grammarAccess.getSequenceAccess().getGroup_15(), "rule__Sequence__Group_15__0");
					put(grammarAccess.getSequenceAccess().getGroup_16(), "rule__Sequence__Group_16__0");
					put(grammarAccess.getSequenceAccess().getGroup_17(), "rule__Sequence__Group_17__0");
					put(grammarAccess.getSequenceAccess().getGroup_18(), "rule__Sequence__Group_18__0");
					put(grammarAccess.getSequenceAccess().getGroup_19(), "rule__Sequence__Group_19__0");
					put(grammarAccess.getDefinitionAccess().getGroup_0(), "rule__Definition__Group_0__0");
					put(grammarAccess.getDefinitionAccess().getGroup_1(), "rule__Definition__Group_1__0");
					put(grammarAccess.getDefinitionAccess().getGroup_2(), "rule__Definition__Group_2__0");
					put(grammarAccess.getDefinitionAccess().getGroup_3(), "rule__Definition__Group_3__0");
					put(grammarAccess.getDefinitionAccess().getGroup_4(), "rule__Definition__Group_4__0");
					put(grammarAccess.getAutoNumberAccess().getGroup(), "rule__AutoNumber__Group__0");
					put(grammarAccess.getAutoNumberAccess().getGroup_1(), "rule__AutoNumber__Group_1__0");
					put(grammarAccess.getColorAccess().getGroup(), "rule__Color__Group__0");
					put(grammarAccess.getModelAccess().getDiagramsAssignment(), "rule__Model__DiagramsAssignment");
					put(grammarAccess.getDiagramAccess().getInstructionsAssignment_1(), "rule__Diagram__InstructionsAssignment_1");
					put(grammarAccess.getInstructionAccess().getName1Assignment_0_0(), "rule__Instruction__Name1Assignment_0_0");
					put(grammarAccess.getInstructionAccess().getName2Assignment_0_2(), "rule__Instruction__Name2Assignment_0_2");
					put(grammarAccess.getDefinitionAccess().getNameAssignment_0_1(), "rule__Definition__NameAssignment_0_1");
					put(grammarAccess.getDefinitionAccess().getNameAssignment_1_1(), "rule__Definition__NameAssignment_1_1");
					put(grammarAccess.getDefinitionAccess().getNameAssignment_2_1(), "rule__Definition__NameAssignment_2_1");
					put(grammarAccess.getDefinitionAccess().getNameAssignment_3_1(), "rule__Definition__NameAssignment_3_1");
					put(grammarAccess.getDefinitionAccess().getNameAssignment_4_1(), "rule__Definition__NameAssignment_4_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.ui.contentassist.antlr.internal.InternalPlantumlParser typedParser = (org.xtext.ui.contentassist.antlr.internal.InternalPlantumlParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_SL_COMMENT" };
	}
	
	public PlantumlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PlantumlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
