/*
 * generated by Xtext
 */
package org.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PlantumlUiModule extends org.xtext.ui.AbstractPlantumlUiModule {
	public PlantumlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	// This will make sure that PlantumlHighlightingConfiguration 
	// is used instead of the default version.
	public Class<? extends IHighlightingConfiguration>
	bindIHighlightingConfiguration () {
		return PlantumlHighlightingConfiguration.class;
	}
	
	// This will make sure that PlantumlHighlightingCalculator
	// is used instead of the default version.
	public Class<? extends ISemanticHighlightingCalculator>
	bindISemanticHIghlightingCalculator(){
		return PlantumlHighlightingCalculator.class;
	}
}
