/*
 * generated by Xtext
 */
package org.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class PlantumlStandaloneSetup extends PlantumlStandaloneSetupGenerated{

	public static void doSetup() {
		new PlantumlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

