/*
 * generated by Xtext
 */
package org.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PlantumlRuntimeModule extends org.xtext.AbstractPlantumlRuntimeModule {

}
